// Auto-generated by `aaa ralph refresh-models`
// Do not edit manually - changes will be overwritten on next refresh
// Generated: (not yet refreshed)

import type { ModelInfo } from "./models-static";

const DISCOVERED_MODELS: Array<ModelInfo> = [];

// eslint-disable-next-line import/prefer-default-export -- named export required for code generation consistency
export { DISCOVERED_MODELS };
