/**
 * Bash completion script generator for aaa CLI
 *
 * Features:
 * - Self-contained (no _init_completion dependency)
 * - While-loop to find subcommand chain (skips flags)
 * - $prev check for flag value completion (highest priority)
 * - Dynamic completions via `aaa __complete <type>`
 * - Falls back to file completion via -o bashdefault -o default
 */
export default function generateBashCompletion(): string {
  return `# aaa bash completion
# Generated by: aaa completion bash
# Install: source <(aaa completion bash)
# Or add to ~/.bashrc: source <(aaa completion bash)

_aaa_completions() {
    local cur prev
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    # PHASE 1: Flag value completion (highest priority)
    case "$prev" in
        --mode)
            COMPREPLY=($(compgen -W "quick deep code" -- "$cur"))
            return
            ;;
        --processor)
            COMPREPLY=($(compgen -W "base pro" -- "$cur"))
            return
            ;;
        --milestone)
            # Dynamic milestone names + directory completion fallback
            local milestones=$(aaa __complete milestone 2>/dev/null)
            COMPREPLY=($(compgen -W "$milestones" -- "$cur"))
            # Also add directory completion
            COMPREPLY+=($(compgen -d -- "$cur"))
            return
            ;;
        --story)
            # Dynamic story names + file completion fallback
            local stories=$(aaa __complete story 2>/dev/null)
            COMPREPLY=($(compgen -W "$stories" -- "$cur"))
            # Also add .md file completion
            COMPREPLY+=($(compgen -f -X '!*.md' -- "$cur"))
            return
            ;;
        --task)
            # Dynamic task names + file completion fallback
            local tasks=$(aaa __complete task 2>/dev/null)
            COMPREPLY=($(compgen -W "$tasks" -- "$cur"))
            # Also add .md file completion
            COMPREPLY+=($(compgen -f -X '!*.md' -- "$cur"))
            return
            ;;
        --subtasks)
            # Complete .json files
            COMPREPLY=($(compgen -f -X '!*.json' -- "$cur"))
            return
            ;;
        --size)
            COMPREPLY=($(compgen -W "small medium large" -- "$cur"))
            return
            ;;
        --cascade)
            # Dynamic cascade targets
            local targets=$(aaa __complete cascade 2>/dev/null)
            COMPREPLY=($(compgen -W "$targets" -- "$cur"))
            return
            ;;
        --calibrate-every)
            # Numeric values - no completion
            return
            ;;
        -o|--output)
            # File path completion
            COMPREPLY=($(compgen -f -- "$cur"))
            return
            ;;
        -d|--dir)
            # Directory completion
            COMPREPLY=($(compgen -d -- "$cur"))
            return
            ;;
        -t|--target)
            # Directory completion
            COMPREPLY=($(compgen -d -- "$cur"))
            return
            ;;
        -l|--limit|-s|--skip|--max-results|--max-chars|--max-iterations)
            # Numeric values - no completion
            return
            ;;
        --objective|--queries)
            # Free text - no completion
            return
            ;;
        --priority)
            COMPREPLY=($(compgen -W "min low default high max" -- "$cur"))
            return
            ;;
        --quiet-enabled)
            COMPREPLY=($(compgen -W "true false" -- "$cur"))
            return
            ;;
    esac

    # PHASE 2: Find subcommand chain (skip flags and their values)
    local cmd="" subcmd="" subsubcmd=""
    local i=1
    local skip_next=false
    while [[ $i -lt $COMP_CWORD ]]; do
        local word="\${COMP_WORDS[i]}"
        if [[ "$skip_next" == "true" ]]; then
            skip_next=false
            ((i++))
            continue
        fi
        case "$word" in
            --mode|--processor|--milestone|--story|--task|--subtasks|--size|--cascade|--calibrate-every|-o|--output|-d|--dir|-t|--target|-l|--limit|-s|--skip|--max-results|--max-chars|--max-iterations|--objective|--queries|--stories-directory)
                # Flag that takes a value - skip next word
                skip_next=true
                ;;
            -*)
                # Other flags (boolean) - skip
                ;;
            *)
                if [[ -z "$cmd" ]]; then
                    cmd="$word"
                elif [[ -z "$subcmd" ]]; then
                    subcmd="$word"
                elif [[ -z "$subsubcmd" ]]; then
                    subsubcmd="$word"
                fi
                ;;
        esac
        ((i++))
    done

    # PHASE 3: Complete flags if typing a dash
    if [[ "$cur" == -* ]]; then
        case "$cmd" in
            extract-conversations)
                COMPREPLY=($(compgen -W "-l --limit -o --output -s --skip" -- "$cur"))
                return
                ;;
            gemini-research)
                COMPREPLY=($(compgen -W "--mode" -- "$cur"))
                return
                ;;
            parallel-search)
                COMPREPLY=($(compgen -W "--objective --queries --processor --max-results --max-chars" -- "$cur"))
                return
                ;;
            setup|uninstall)
                COMPREPLY=($(compgen -W "--user --project" -- "$cur"))
                return
                ;;
            sync-context)
                COMPREPLY=($(compgen -W "-t --target -w --watch" -- "$cur"))
                return
                ;;
            task)
                if [[ "$subcmd" == "create" ]]; then
                    COMPREPLY=($(compgen -W "-d --dir -s --story" -- "$cur"))
                fi
                return
                ;;
            story)
                if [[ "$subcmd" == "create" ]]; then
                    COMPREPLY=($(compgen -W "-d --dir" -- "$cur"))
                fi
                return
                ;;
            ralph)
                case "$subcmd" in
                    build)
                        COMPREPLY=($(compgen -W "--subtasks -p --print -i --interactive -s --supervised -H --headless --max-iterations --validate-first --cascade --calibrate-every" -- "$cur"))
                        return
                        ;;
                    plan)
                        case "$subsubcmd" in
                            stories)
                                COMPREPLY=($(compgen -W "--milestone -a --auto -s --supervised -H --headless --cascade" -- "$cur"))
                                return
                                ;;
                            tasks)
                                COMPREPLY=($(compgen -W "--story --milestone -a --auto -s --supervised -H --headless --cascade" -- "$cur"))
                                return
                                ;;
                            subtasks)
                                COMPREPLY=($(compgen -W "--review --task --story --milestone --size -s --supervised -H --headless --cascade --calibrate-every --file --text" -- "$cur"))
                                return
                                ;;
                        esac
                        ;;
                    milestones)
                        COMPREPLY=($(compgen -W "--json" -- "$cur"))
                        return
                        ;;
                    status)
                        COMPREPLY=($(compgen -W "--subtasks" -- "$cur"))
                        return
                        ;;
                    calibrate)
                        COMPREPLY=($(compgen -W "--force --review" -- "$cur"))
                        return
                        ;;
                    review)
                        # All review commands are supervised-only (no headless)
                        ;;
                    archive)
                        if [[ "$subsubcmd" == "subtasks" ]]; then
                            COMPREPLY=($(compgen -W "--subtasks --milestone" -- "$cur"))
                        fi
                        return
                        ;;
                esac
                ;;
            review)
                if [[ -z "$subcmd" ]]; then
                    COMPREPLY=($(compgen -W "-s --supervised -H --headless --dry-run" -- "$cur"))
                fi
                return
                ;;
            session)
                case "$subcmd" in
                    path|cat)
                        COMPREPLY=($(compgen -W "--commit" -- "$cur"))
                        ;;
                    list)
                        COMPREPLY=($(compgen -W "--limit --verbose" -- "$cur"))
                        ;;
                esac
                return
                ;;
            notify)
                if [[ -z "$subcmd" ]]; then
                    COMPREPLY=($(compgen -W "-t --title -p --priority --tags -q --quiet --dry-run --event" -- "$cur"))
                elif [[ "$subcmd" == "config" ]]; then
                    case "$subsubcmd" in
                        set)
                            COMPREPLY=($(compgen -W "--topic --server --title --priority --quiet-start --quiet-end --quiet-enabled" -- "$cur"))
                            ;;
                        show)
                            COMPREPLY=($(compgen -W "--json" -- "$cur"))
                            ;;
                        test)
                            COMPREPLY=($(compgen -W "-m --message" -- "$cur"))
                            ;;
                    esac
                fi
                return
                ;;
        esac
        # Global flags
        COMPREPLY=($(compgen -W "-h --help -V --version" -- "$cur"))
        return
    fi

    # PHASE 4: Command/subcommand completion
    case "$cmd" in
        "")
            # Top-level commands
            COMPREPLY=($(compgen -W "extract-conversations gh-search gemini-research notify parallel-search session setup uninstall sync-context task story ralph review completion" -- "$cur"))
            ;;
        task)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "create" -- "$cur"))
            fi
            ;;
        story)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "create" -- "$cur"))
            fi
            ;;
        ralph)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "build plan review milestones status calibrate archive" -- "$cur"))
            elif [[ "$subcmd" == "plan" && -z "$subsubcmd" ]]; then
                COMPREPLY=($(compgen -W "vision roadmap stories tasks subtasks" -- "$cur"))
            elif [[ "$subcmd" == "review" && -z "$subsubcmd" ]]; then
                COMPREPLY=($(compgen -W "stories roadmap gap tasks" -- "$cur"))
            elif [[ "$subcmd" == "review" && "$subsubcmd" == "gap" ]]; then
                # ralph review gap subcommands
                COMPREPLY=($(compgen -W "roadmap stories" -- "$cur"))
            elif [[ "$subcmd" == "calibrate" && -z "$subsubcmd" ]]; then
                COMPREPLY=($(compgen -W "intention technical improve all" -- "$cur"))
            elif [[ "$subcmd" == "archive" && -z "$subsubcmd" ]]; then
                COMPREPLY=($(compgen -W "subtasks progress" -- "$cur"))
            fi
            ;;
        review)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "status" -- "$cur"))
            fi
            ;;
        notify)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "init on off status config" -- "$cur"))
            elif [[ "$subcmd" == "config" && -z "$subsubcmd" ]]; then
                COMPREPLY=($(compgen -W "set show test" -- "$cur"))
            fi
            ;;
        completion)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
            fi
            ;;
        session)
            if [[ -z "$subcmd" ]]; then
                COMPREPLY=($(compgen -W "path current cat list" -- "$cur"))
            fi
            ;;
    esac
}

complete -o bashdefault -o default -F _aaa_completions aaa
`;
}
