/**
 * Fish completion script generator for aaa CLI
 *
 * Features:
 * - complete -c aaa with -f to disable file completion by default
 * - Condition functions for subcommand context
 * - Dynamic completions via `aaa __complete <type>`
 */
export default function generateFishCompletion(): string {
  return `# aaa fish completion
# Generated by: aaa completion fish
# Install: aaa completion fish > ~/.config/fish/completions/aaa.fish

# Disable file completion by default
complete -c aaa -f

# Helper functions
function __fish_aaa_using_subcommand
    set -l cmd (commandline -opc)
    set -l count (count $cmd)
    if test $count -ge 2
        if test "$argv[1]" = "$cmd[2]"
            return 0
        end
    end
    return 1
end

function __fish_aaa_using_subsubcommand
    set -l cmd (commandline -opc)
    set -l count (count $cmd)
    if test $count -ge 3
        if test "$argv[1]" = "$cmd[2]" -a "$argv[2]" = "$cmd[3]"
            return 0
        end
    end
    return 1
end

function __fish_aaa_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

# Top-level commands
complete -c aaa -n __fish_aaa_needs_command -a download -d 'Download URLs, extract text, save as markdown'
complete -c aaa -n __fish_aaa_needs_command -a extract-conversations -d 'Extract Claude Code conversation history'
complete -c aaa -n __fish_aaa_needs_command -a gh-search -d 'Search GitHub for code examples'
complete -c aaa -n __fish_aaa_needs_command -a gemini-research -d 'Google Search via Gemini CLI'
complete -c aaa -n __fish_aaa_needs_command -a parallel-search -d 'Multi-angle web research'
complete -c aaa -n __fish_aaa_needs_command -a setup -d 'Setup all-agents for user or project'
complete -c aaa -n __fish_aaa_needs_command -a uninstall -d 'Uninstall all-agents'
complete -c aaa -n __fish_aaa_needs_command -a sync-context -d 'Sync context folder to target project'
complete -c aaa -n __fish_aaa_needs_command -a task -d 'Task management utilities'
complete -c aaa -n __fish_aaa_needs_command -a story -d 'Story management utilities'
complete -c aaa -n __fish_aaa_needs_command -a ralph -d 'Autonomous development framework'
complete -c aaa -n __fish_aaa_needs_command -a review -d 'Run parallel multi-agent code review'
complete -c aaa -n __fish_aaa_needs_command -a completion -d 'Generate shell completion scripts'

# Global options
complete -c aaa -s h -l help -d 'Show help'
complete -c aaa -s V -l version -d 'Show version'

# download options
complete -c aaa -n '__fish_aaa_using_subcommand download' -s o -l output -d 'Output filename' -r
complete -c aaa -n '__fish_aaa_using_subcommand download' -s d -l dir -d 'Output directory' -ra '(__fish_complete_directories)'

# extract-conversations options
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s l -l limit -d 'Number of recent conversations' -r
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s o -l output -d 'Output file' -r
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s s -l skip -d 'Skip N most recent' -r

# gemini-research options
complete -c aaa -n '__fish_aaa_using_subcommand gemini-research' -l mode -d 'Research mode' -xa 'quick deep code'

# parallel-search options
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l objective -d 'Main search objective' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l queries -d 'Additional search queries' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l processor -d 'Processing level' -xa 'base pro'
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l max-results -d 'Maximum results' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l max-chars -d 'Max chars per excerpt' -r

# setup options
complete -c aaa -n '__fish_aaa_using_subcommand setup' -l user -d 'Setup CLI globally'
complete -c aaa -n '__fish_aaa_using_subcommand setup' -l project -d 'Setup current project'

# uninstall options
complete -c aaa -n '__fish_aaa_using_subcommand uninstall' -l user -d 'Remove aaa symlink'
complete -c aaa -n '__fish_aaa_using_subcommand uninstall' -l project -d 'Remove context/ symlink'

# sync-context options
complete -c aaa -n '__fish_aaa_using_subcommand sync-context' -s t -l target -d 'Target directory' -ra '(__fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subcommand sync-context' -s w -l watch -d 'Watch for changes'

# task subcommands
complete -c aaa -n '__fish_aaa_using_subcommand task' -a create -d 'Create empty task file'
complete -c aaa -n '__fish_aaa_using_subsubcommand task create' -s d -l dir -d 'Custom tasks directory' -ra '(__fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subsubcommand task create' -s s -l story -d 'Link task to story number' -r

# story subcommands
complete -c aaa -n '__fish_aaa_using_subcommand story' -a create -d 'Create empty story file'
complete -c aaa -n '__fish_aaa_using_subsubcommand story create' -s d -l dir -d 'Custom stories directory' -ra '(__fish_complete_directories)'

# ralph subcommands
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a build -d 'Run subtask iteration loop'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a plan -d 'Planning tools'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a review -d 'Review planning artifacts'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a milestones -d 'List available milestones'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a status -d 'Display build status'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a calibrate -d 'Run calibration checks'

# ralph build options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s p -l print -d 'Print prompt without executing'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s i -l interactive -d 'Pause between iterations (legacy)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s s -l supervised -d 'Supervised mode: watch each iteration'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s H -l headless -d 'Headless mode: JSON output + logging'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l max-iterations -d 'Max retry attempts' -r
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l validate-first -d 'Run pre-build validation'

# ralph status options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph status' -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'

# ralph plan subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a vision -d 'Interactive vision planning'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a roadmap -d 'Interactive roadmap planning'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a stories -d 'Story planning for a milestone'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a tasks -d 'Task planning for a story'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a subtasks -d 'Generate subtasks for a task'

# ralph plan stories options
function __fish_aaa_ralph_plan_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = stories
end
complete -c aaa -n __fish_aaa_ralph_plan_stories -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -s a -l auto -d 'Use auto mode (alias for --supervised)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -s s -l supervised -d 'Supervised mode: watch chat'
complete -c aaa -n __fish_aaa_ralph_plan_stories -s H -l headless -d 'Headless mode: JSON output + logging'

# ralph plan tasks options
function __fish_aaa_ralph_plan_tasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = tasks
end
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l story -d 'Story file' -ra '(__fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -s a -l auto -d 'Use auto mode (alias for --supervised)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -s s -l supervised -d 'Supervised mode: watch chat'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -s H -l headless -d 'Headless mode: JSON output + logging'

# ralph plan subtasks options
function __fish_aaa_ralph_plan_subtasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = subtasks
end
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l task -d 'Task file' -ra '(__fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -s s -l supervised -d 'Supervised mode (default)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -s H -l headless -d 'Headless mode: JSON output + logging'

# ralph milestones options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph milestones' -l json -d 'Output as JSON'

# ralph calibrate options and subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a intention -d 'Check for intention drift'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a technical -d 'Check for technical drift'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a improve -d 'Self-improvement analysis'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a all -d 'Run all checks'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -l force -d 'Skip approval'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -l review -d 'Require approval'

# ralph review subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a stories -d 'Review stories for a milestone'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a roadmap -d 'Review roadmap milestones'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a gap -d 'Cold analysis for gaps'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a tasks -d 'Review tasks (coming soon)'

# ralph review - all supervised-only (no headless, review is dialogue)

# ralph review stories needs milestone argument
function __fish_aaa_ralph_review_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = stories
end
complete -c aaa -n __fish_aaa_ralph_review_stories -xa '(aaa __complete milestone 2>/dev/null)'

# ralph review roadmap - no additional options

# ralph review gap subcommands
function __fish_aaa_ralph_review_gap
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap
end
complete -c aaa -n __fish_aaa_ralph_review_gap -a roadmap -d 'Gap analysis of roadmap'
complete -c aaa -n __fish_aaa_ralph_review_gap -a stories -d 'Gap analysis of stories'

# ralph review gap - supervised only (no headless, requires human judgment)

# ralph review gap stories needs milestone argument
function __fish_aaa_ralph_review_gap_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 5 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap -a "$cmd[5]" = stories
end
complete -c aaa -n __fish_aaa_ralph_review_gap_stories -xa '(aaa __complete milestone 2>/dev/null)'

# review options and subcommands
complete -c aaa -n '__fish_aaa_using_subcommand review' -s s -l supervised -d 'Supervised mode: watch execution'
complete -c aaa -n '__fish_aaa_using_subcommand review' -s H -l headless -d 'Headless mode: fully autonomous'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l dry-run -d 'Preview findings without fixing (requires --headless)'
complete -c aaa -n '__fish_aaa_using_subcommand review' -a status -d 'Display review history and statistics'

# completion subcommands
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a bash -d 'Generate bash completion'
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a zsh -d 'Generate zsh completion'
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a fish -d 'Generate fish completion'
`;
}
