/**
 * Fish completion script generator for aaa CLI
 *
 * Features:
 * - complete -c aaa with -f to disable file completion by default
 * - Condition functions for subcommand context
 * - Dynamic completions via `aaa __complete <type>`
 */
export default function generateFishCompletion(): string {
  return `# aaa fish completion
# Generated by: aaa completion fish
# Install: aaa completion fish > ~/.config/fish/completions/aaa.fish

# Disable file completion by default
complete -c aaa -f

# Helper functions
function __fish_aaa_using_subcommand
    set -l cmd (commandline -opc)
    set -l count (count $cmd)
    if test $count -ge 2
        if test "$argv[1]" = "$cmd[2]"
            return 0
        end
    end
    return 1
end

function __fish_aaa_using_subsubcommand
    set -l cmd (commandline -opc)
    set -l count (count $cmd)
    if test $count -ge 3
        if test "$argv[1]" = "$cmd[2]" -a "$argv[2]" = "$cmd[3]"
            return 0
        end
    end
    return 1
end

function __fish_aaa_needs_command
    set -l cmd (commandline -opc)
    test (count $cmd) -eq 1
end

function __fish_aaa_model_completions
    set -l cmd (commandline -opc)
    set -l count (count $cmd)
    set -l provider ""
    set -l i 1

    while test $i -le $count
        if test "$cmd[$i]" = "--provider"
            set -l next (math $i + 1)
            if test $next -le $count
                set provider "$cmd[$next]"
                break
            end
        end
        set i (math $i + 1)
    end

    if test -n "$provider"
        aaa __complete model --provider "$provider" 2>/dev/null | while read line
            set -l parts (string split \t $line)
            if test (count $parts) -ge 2
                echo $parts[1]\t$parts[2]
            else if test (count $parts) -eq 1
                echo $parts[1]
            end
        end
    else
        aaa __complete model 2>/dev/null | while read line
            set -l parts (string split \t $line)
            if test (count $parts) -ge 2
                echo $parts[1]\t$parts[2]
            else if test (count $parts) -eq 1
                echo $parts[1]
            end
        end
    end
end

# Top-level commands
complete -c aaa -n __fish_aaa_needs_command -a extract-conversations -d 'Extract Claude Code conversation history'
complete -c aaa -n __fish_aaa_needs_command -a gh-search -d 'Search GitHub for code examples'
complete -c aaa -n __fish_aaa_needs_command -a gemini-research -d 'Google Search via Gemini CLI'
complete -c aaa -n __fish_aaa_needs_command -a parallel-search -d 'Multi-angle web research'
complete -c aaa -n __fish_aaa_needs_command -a setup -d 'Setup all-agents for user or project'
complete -c aaa -n __fish_aaa_needs_command -a uninstall -d 'Uninstall all-agents'
complete -c aaa -n __fish_aaa_needs_command -a sync-context -d 'Sync context folder to target project'
complete -c aaa -n __fish_aaa_needs_command -a task -d 'Task management utilities'
complete -c aaa -n __fish_aaa_needs_command -a story -d 'Story management utilities'
complete -c aaa -n __fish_aaa_needs_command -a ralph -d 'Autonomous development framework'
complete -c aaa -n __fish_aaa_needs_command -a review -d 'Run parallel multi-agent code review'
complete -c aaa -n __fish_aaa_needs_command -a notify -d 'Push notifications via ntfy.sh'
complete -c aaa -n __fish_aaa_needs_command -a session -d 'Manage and retrieve Claude session files'
complete -c aaa -n __fish_aaa_needs_command -a completion -d 'Generate shell completion scripts'

# Global options
complete -c aaa -s h -l help -d 'Show help'
complete -c aaa -s V -l version -d 'Show version'

# extract-conversations options
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s l -l limit -d 'Number of recent conversations' -r
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s o -l output -d 'Output file' -r
complete -c aaa -n '__fish_aaa_using_subcommand extract-conversations' -s s -l skip -d 'Skip N most recent' -r

# gemini-research options
complete -c aaa -n '__fish_aaa_using_subcommand gemini-research' -l mode -d 'Research mode' -xa 'quick deep code'

# parallel-search options
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l objective -d 'Main search objective' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l queries -d 'Additional search queries' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l processor -d 'Processing level' -xa 'base pro'
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l max-results -d 'Maximum results' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -l max-chars -d 'Max chars per excerpt' -r
complete -c aaa -n '__fish_aaa_using_subcommand parallel-search' -s v -l verbose -d 'Show full report content instead of summary'

# setup options
complete -c aaa -n '__fish_aaa_using_subcommand setup' -l user -d 'Setup CLI globally'
complete -c aaa -n '__fish_aaa_using_subcommand setup' -l project -d 'Setup current project'

# uninstall options
complete -c aaa -n '__fish_aaa_using_subcommand uninstall' -l user -d 'Remove aaa symlink'
complete -c aaa -n '__fish_aaa_using_subcommand uninstall' -l project -d 'Remove context/ symlink'

# sync-context options
complete -c aaa -n '__fish_aaa_using_subcommand sync-context' -s t -l target -d 'Target directory' -ra '(__fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subcommand sync-context' -s w -l watch -d 'Watch for changes'

# notify options and subcommands
complete -c aaa -n '__fish_aaa_using_subcommand notify' -s t -l title -d 'Notification title' -r
complete -c aaa -n '__fish_aaa_using_subcommand notify' -s p -l priority -d 'Priority level' -xa 'min low default high max'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -l tags -d 'Comma-separated tags/emojis' -r
complete -c aaa -n '__fish_aaa_using_subcommand notify' -s q -l quiet -d 'Suppress output on success'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -l dry-run -d 'Show what would be sent without sending'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -l event -d 'Event name for routing' -r
complete -c aaa -n '__fish_aaa_using_subcommand notify' -a init -d 'Interactive first-time setup'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -a on -d 'Enable notifications'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -a off -d 'Disable notifications'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -a status -d 'Show current notification status'
complete -c aaa -n '__fish_aaa_using_subcommand notify' -a config -d 'Configuration management'

# notify config subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand notify config' -a set -d 'Set configuration values'
complete -c aaa -n '__fish_aaa_using_subsubcommand notify config' -a show -d 'Display current configuration'
complete -c aaa -n '__fish_aaa_using_subsubcommand notify config' -a test -d 'Send a test notification'

# notify config set options
function __fish_aaa_notify_config_set
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = notify -a "$cmd[3]" = config -a "$cmd[4]" = set
end
complete -c aaa -n __fish_aaa_notify_config_set -l topic -d 'Set ntfy topic' -r
complete -c aaa -n __fish_aaa_notify_config_set -l server -d 'Set ntfy server URL' -r
complete -c aaa -n __fish_aaa_notify_config_set -l title -d 'Set default notification title' -r
complete -c aaa -n __fish_aaa_notify_config_set -l priority -d 'Set default priority' -xa 'min low default high max'
complete -c aaa -n __fish_aaa_notify_config_set -l quiet-start -d 'Set quiet hours start (0-23)' -r
complete -c aaa -n __fish_aaa_notify_config_set -l quiet-end -d 'Set quiet hours end (0-23)' -r
complete -c aaa -n __fish_aaa_notify_config_set -l quiet-enabled -d 'Enable/disable quiet hours' -xa 'true false'

# notify config show options
function __fish_aaa_notify_config_show
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = notify -a "$cmd[3]" = config -a "$cmd[4]" = show
end
complete -c aaa -n __fish_aaa_notify_config_show -l json -d 'Output as JSON'

# notify config test options
function __fish_aaa_notify_config_test
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = notify -a "$cmd[3]" = config -a "$cmd[4]" = test
end
complete -c aaa -n __fish_aaa_notify_config_test -s m -l message -d 'Custom test message' -r

# task subcommands
complete -c aaa -n '__fish_aaa_using_subcommand task' -a create -d 'Create empty task file'
complete -c aaa -n '__fish_aaa_using_subsubcommand task create' -s d -l dir -d 'Custom tasks directory' -ra '(__fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subsubcommand task create' -s m -l milestone -d 'Milestone name/path' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subsubcommand task create' -s s -l story -d 'Link task to story number' -r

# story subcommands
complete -c aaa -n '__fish_aaa_using_subcommand story' -a create -d 'Create empty story file'
complete -c aaa -n '__fish_aaa_using_subsubcommand story create' -s d -l dir -d 'Custom stories directory' -ra '(__fish_complete_directories)'
complete -c aaa -n '__fish_aaa_using_subsubcommand story create' -s m -l milestone -d 'Milestone name/path' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'

# ralph subcommands
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a build -d 'Run subtask iteration loop'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a plan -d 'Planning tools'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a review -d 'Review planning artifacts'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a milestones -d 'List available milestones'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a models -d 'List available model names'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a status -d 'Display build status'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a subtasks -d 'Subtask queue operations'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a calibrate -d 'Run calibration checks'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a archive -d 'Archive subtasks and sessions'
complete -c aaa -n '__fish_aaa_using_subcommand ralph' -a refresh-models -d 'Discover models from CLI providers'

# ralph build options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s p -l print -d 'Print prompt without executing'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s i -l interactive -d 'Pause between iterations (legacy)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s s -l supervised -d 'Supervised mode: watch each iteration'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s H -l headless -d 'Headless mode: JSON output + logging'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s q -l quiet -d 'Suppress terminal summary output'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -s S -l skip-summary -d 'Skip summary generation in headless mode'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l max-iterations -d 'Max retry attempts' -r
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l validate-first -d 'Validate first; may create/update/remove/reorder/split pending queue order'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l cascade -d 'Cascade to target level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l calibrate-every -d 'Run calibration every N iterations; may insert corrective queue-order subtasks' -r
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l force -d 'Approval mode: auto-apply validation/calibration queue proposals'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l review -d 'Approval mode: require explicit approval for validation/calibration queue proposals'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l from -d 'Resume cascade from this level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l dry-run -d 'Show execution plan without executing'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph build' -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'

# ralph status options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph status' -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'

# ralph plan subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a vision -d 'Interactive vision planning'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a roadmap -d 'Interactive roadmap planning'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a stories -d 'Story planning for a milestone'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a tasks -d 'Task planning for a story'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph plan' -a subtasks -d 'Generate subtasks for a task'

# ralph plan vision options
function __fish_aaa_ralph_plan_vision
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = vision
end
complete -c aaa -n __fish_aaa_ralph_plan_vision -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_vision -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'

# ralph plan roadmap options
function __fish_aaa_ralph_plan_roadmap
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = roadmap
end
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l force -d 'Skip all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l review -d 'Require all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l from -d 'Resume cascade from this level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l cascade -d 'Cascade to target level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l dry-run -d 'Show execution plan without executing'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_roadmap -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'

# ralph plan stories options
function __fish_aaa_ralph_plan_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = stories
end
complete -c aaa -n __fish_aaa_ralph_plan_stories -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -s s -l supervised -d 'Supervised mode: watch chat'
complete -c aaa -n __fish_aaa_ralph_plan_stories -s H -l headless -d 'Headless mode: JSON output + logging'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l force -d 'Skip all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l review -d 'Require all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l from -d 'Resume cascade from this level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l cascade -d 'Cascade to target level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_stories -l dry-run -d 'Show execution plan without executing'

# ralph plan tasks options
function __fish_aaa_ralph_plan_tasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = tasks
end
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l story -d 'Story file' -xa '(aaa __complete story 2>/dev/null; __fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l file -d 'Source file path' -ra '(__fish_complete_path)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l text -d 'Source text description' -r
complete -c aaa -n __fish_aaa_ralph_plan_tasks -s s -l supervised -d 'Supervised mode: watch chat'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -s H -l headless -d 'Headless mode: JSON output + logging'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l force -d 'Skip all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l review -d 'Require all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l from -d 'Resume cascade from this level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l cascade -d 'Cascade to target level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_tasks -l dry-run -d 'Show execution plan without executing'

# ralph plan subtasks options
function __fish_aaa_ralph_plan_subtasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = plan -a "$cmd[4]" = subtasks
end
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l task -d 'Task file (legacy)' -xa '(aaa __complete task 2>/dev/null; __fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l force -d 'Skip all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l review -d 'Require all approval prompts'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l review-diary -d 'Parse logs/reviews.jsonl for findings'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l from -d 'Resume cascade from this level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l story -d 'Link subtasks to parent story' -xa '(aaa __complete story 2>/dev/null; __fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l milestone -d 'Target milestone' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l output-dir -d 'Output directory (path or milestone name)' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l size -d 'Slice thickness' -xa 'small medium large'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -s s -l supervised -d 'Supervised mode (default)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -s H -l headless -d 'Headless mode: JSON output + logging'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l cascade -d 'Cascade to target level' -xa '(aaa __complete cascade 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l calibrate-every -d 'Run calibration every N iterations' -r
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l validate-first -d 'Run pre-build validation before cascading build'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l dry-run -d 'Show execution plan without executing'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l file -d 'Source file path' -ra '(__fish_complete_path)'
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -l text -d 'Source text description' -r
# Enable file completion for positional [source] argument
complete -c aaa -n __fish_aaa_ralph_plan_subtasks -F

# ralph milestones options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph milestones' -l json -d 'Output as JSON'

# ralph models options
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph models' -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph models' -l json -d 'Output as JSON'

# ralph subtasks subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a next -d 'Get next subtask in queue order'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a list -d 'List subtasks for a milestone queue'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a complete -d 'Mark a subtask complete'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a append -d 'Append subtasks to the end of queue order'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a prepend -d 'Prepend subtasks to the front of queue order'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a diff -d 'Preview queue-order changes from a proposal'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph subtasks' -a apply -d 'Apply queue-order changes from a proposal'

# ralph subtasks next options
function __fish_aaa_ralph_subtasks_next
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = next
end
complete -c aaa -n __fish_aaa_ralph_subtasks_next -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_subtasks_next -l json -d 'Output as JSON'

# ralph subtasks list options
function __fish_aaa_ralph_subtasks_list
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = list
end
complete -c aaa -n __fish_aaa_ralph_subtasks_list -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_subtasks_list -l pending -d 'Only show pending subtasks'
complete -c aaa -n __fish_aaa_ralph_subtasks_list -l limit -d 'Maximum subtasks to show' -r
complete -c aaa -n __fish_aaa_ralph_subtasks_list -l json -d 'Output as JSON'

# ralph subtasks complete options
function __fish_aaa_ralph_subtasks_complete
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = complete
end
complete -c aaa -n __fish_aaa_ralph_subtasks_complete -l milestone -d 'Milestone name' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'
complete -c aaa -n __fish_aaa_ralph_subtasks_complete -l id -d 'Subtask ID' -r
complete -c aaa -n __fish_aaa_ralph_subtasks_complete -l commit -d 'Commit hash' -r
complete -c aaa -n __fish_aaa_ralph_subtasks_complete -l session -d 'Session ID' -r
complete -c aaa -n __fish_aaa_ralph_subtasks_complete -l at -d 'Completion timestamp (ISO 8601)' -r

# ralph subtasks append options
function __fish_aaa_ralph_subtasks_append
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = append
end
complete -c aaa -n __fish_aaa_ralph_subtasks_append -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_subtasks_append -l file -d 'Read subtask JSON from file' -ra '(__fish_complete_path)'
complete -c aaa -n __fish_aaa_ralph_subtasks_append -l dry-run -d 'Show JSON preview without writing queue file'

# ralph subtasks prepend options
function __fish_aaa_ralph_subtasks_prepend
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = prepend
end
complete -c aaa -n __fish_aaa_ralph_subtasks_prepend -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_subtasks_prepend -l file -d 'Read subtask JSON from file' -ra '(__fish_complete_path)'
complete -c aaa -n __fish_aaa_ralph_subtasks_prepend -l dry-run -d 'Show JSON preview without writing queue file'

# ralph subtasks diff options
function __fish_aaa_ralph_subtasks_diff
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = diff
end
complete -c aaa -n __fish_aaa_ralph_subtasks_diff -l proposal -d 'Queue proposal JSON file' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_subtasks_diff -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_subtasks_diff -l json -d 'Output machine-readable JSON summary'

# ralph subtasks apply options
function __fish_aaa_ralph_subtasks_apply
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = subtasks -a "$cmd[4]" = apply
end
complete -c aaa -n __fish_aaa_ralph_subtasks_apply -l proposal -d 'Queue proposal JSON file' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_subtasks_apply -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'

# ralph calibrate options and subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a intention -d 'Check for intention drift'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a technical -d 'Check for technical drift'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a improve -d 'Self-improvement analysis'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -a all -d 'Run all checks'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -l force -d 'Skip approval'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -l review -d 'Require approval'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph calibrate' -l dry-run -d 'Show execution plan without executing'

# ralph archive subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph archive' -a subtasks -d 'Archive completed subtasks'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph archive' -a progress -d 'Archive old sessions from PROGRESS.md'

# ralph archive subtasks options
function __fish_aaa_ralph_archive_subtasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = archive -a "$cmd[4]" = subtasks
end
complete -c aaa -n __fish_aaa_ralph_archive_subtasks -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_archive_subtasks -l milestone -d 'Target milestone' -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'

# ralph archive progress options
function __fish_aaa_ralph_archive_progress
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = archive -a "$cmd[4]" = progress
end
complete -c aaa -n __fish_aaa_ralph_archive_progress -l progress -d 'PROGRESS.md file path' -ra '(__fish_complete_suffix .md)'

# ralph refresh-models options
function __fish_aaa_ralph_refresh_models
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 3 -a "$cmd[2]" = ralph -a "$cmd[3]" = refresh-models
end
complete -c aaa -n __fish_aaa_ralph_refresh_models -l dry-run -d 'Show what would be discovered without writing'
complete -c aaa -n __fish_aaa_ralph_refresh_models -l provider -d 'Discover models from specific provider only' -xa '(aaa __complete provider 2>/dev/null)'

# ralph review subcommands
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a stories -d 'Review stories for a milestone'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a roadmap -d 'Review roadmap milestones'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a gap -d 'Cold analysis for gaps'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a tasks -d 'Review tasks for a story'
complete -c aaa -n '__fish_aaa_using_subsubcommand ralph review' -a subtasks -d 'Review subtask queue before building'

# ralph review tasks options
function __fish_aaa_ralph_review_tasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = tasks
end
complete -c aaa -n __fish_aaa_ralph_review_tasks -l story -d 'Story path to review tasks for' -xa '(aaa __complete story 2>/dev/null; __fish_complete_suffix .md)'
complete -c aaa -n __fish_aaa_ralph_review_tasks -s H -l headless -d 'Headless mode: JSON output + logging'

# ralph review subtasks options
function __fish_aaa_ralph_review_subtasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = subtasks
end
complete -c aaa -n __fish_aaa_ralph_review_subtasks -l subtasks -d 'Subtasks file path to review' -ra '(__fish_complete_suffix .json)'
complete -c aaa -n __fish_aaa_ralph_review_subtasks -s H -l headless -d 'Headless mode: JSON output + logging'

# ralph review stories needs milestone argument
function __fish_aaa_ralph_review_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = stories
end
complete -c aaa -n __fish_aaa_ralph_review_stories -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'

# ralph review roadmap - no additional options

# ralph review gap subcommands
function __fish_aaa_ralph_review_gap
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 4 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap
end
complete -c aaa -n __fish_aaa_ralph_review_gap -a roadmap -d 'Gap analysis of roadmap'
complete -c aaa -n __fish_aaa_ralph_review_gap -a stories -d 'Gap analysis of stories'
complete -c aaa -n __fish_aaa_ralph_review_gap -a tasks -d 'Gap analysis of tasks'
complete -c aaa -n __fish_aaa_ralph_review_gap -a subtasks -d 'Gap analysis of subtask queue'

# ralph review gap tasks options
function __fish_aaa_ralph_review_gap_tasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 5 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap -a "$cmd[5]" = tasks
end
complete -c aaa -n __fish_aaa_ralph_review_gap_tasks -l story -d 'Story path' -xa '(aaa __complete story 2>/dev/null; __fish_complete_suffix .md)'

# ralph review gap subtasks options
function __fish_aaa_ralph_review_gap_subtasks
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 5 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap -a "$cmd[5]" = subtasks
end
complete -c aaa -n __fish_aaa_ralph_review_gap_subtasks -l subtasks -d 'Subtasks file path' -ra '(__fish_complete_suffix .json)'

# ralph review gap stories needs milestone argument
function __fish_aaa_ralph_review_gap_stories
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 5 -a "$cmd[2]" = ralph -a "$cmd[3]" = review -a "$cmd[4]" = gap -a "$cmd[5]" = stories
end
complete -c aaa -n __fish_aaa_ralph_review_gap_stories -xa '(aaa __complete milestone 2>/dev/null; __fish_complete_directories)'

# review options and subcommands
complete -c aaa -n '__fish_aaa_using_subcommand review' -s s -l supervised -d 'Supervised mode: watch execution'
complete -c aaa -n '__fish_aaa_using_subcommand review' -s H -l headless -d 'Headless mode: fully autonomous'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l dry-run -d 'Preview findings without fixing (requires --headless)'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l require-approval -d 'Pause after triage for user confirmation (requires --headless)'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l base -d 'Compare HEAD against specified branch' -r
complete -c aaa -n '__fish_aaa_using_subcommand review' -l range -d 'Compare specific commits (format: from..to)' -r
complete -c aaa -n '__fish_aaa_using_subcommand review' -l staged-only -d 'Review only staged changes'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l unstaged-only -d 'Review only unstaged changes'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l provider -d 'AI provider' -xa '(aaa __complete provider 2>/dev/null)'
complete -c aaa -n '__fish_aaa_using_subcommand review' -l model -d 'Model to use' -xa '(__fish_aaa_model_completions)'
complete -c aaa -n '__fish_aaa_using_subcommand review' -a status -d 'Display review history and statistics'

# completion subcommands
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a bash -d 'Generate bash completion'
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a zsh -d 'Generate zsh completion'
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a fish -d 'Generate fish completion'
complete -c aaa -n '__fish_aaa_using_subcommand completion' -a table -d 'Generate command-option table'

# completion table options
function __fish_aaa_completion_table
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 3 -a "$cmd[2]" = completion -a "$cmd[3]" = table
end
complete -c aaa -n __fish_aaa_completion_table -l format -d 'Output format' -xa 'markdown json'

# session subcommands
complete -c aaa -n '__fish_aaa_using_subcommand session' -a path -d 'Get session file path'
complete -c aaa -n '__fish_aaa_using_subcommand session' -a current -d 'Get current session ID'
complete -c aaa -n '__fish_aaa_using_subcommand session' -a cat -d 'Output session JSONL content'
complete -c aaa -n '__fish_aaa_using_subcommand session' -a list -d 'List recent sessions'

# session path/cat options
function __fish_aaa_session_path_or_cat
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 3 -a "$cmd[2]" = session -a \\( "$cmd[3]" = path -o "$cmd[3]" = cat \\)
end
complete -c aaa -n __fish_aaa_session_path_or_cat -l commit -d 'Extract session ID from commit trailer' -r
complete -c aaa -n __fish_aaa_session_path_or_cat -l id -d 'Session ID to look up' -xa '(aaa __complete session-id 2>/dev/null)'

# session list options
function __fish_aaa_session_list
    set -l cmd (commandline -opc)
    test (count $cmd) -ge 3 -a "$cmd[2]" = session -a "$cmd[3]" = list
end
complete -c aaa -n __fish_aaa_session_list -l limit -d 'Limit output to N entries' -r
complete -c aaa -n __fish_aaa_session_list -l verbose -d 'Human-readable table format'
`;
}
