/* eslint-disable no-useless-escape -- Template generates zsh code requiring \$ literals */
/**
 * Zsh completion script generator for aaa CLI
 *
 * Features:
 * - #compdef aaa header for automatic loading
 * - _arguments with state machine for nested commands
 * - _describe for command descriptions
 * - Dynamic completions via `aaa __complete <type>`
 */
export default function generateZshCompletion(): string {
  return `#compdef aaa
# aaa zsh completion
# Generated by: aaa completion zsh
# Install: source <(aaa completion zsh)
# For oh-my-zsh: aaa completion zsh > ~/.oh-my-zsh/completions/_aaa
# Note: Works with lazy compinit (zinit, etc.) - compdef is deferred if not available

_aaa() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \\
        '(-h --help)'{-h,--help}'[Show help]' \\
        '(-V --version)'{-V,--version}'[Show version]' \\
        '1: :->command' \\
        '*:: :->args'

    case $state in
        command)
            local -a commands
            commands=(
                'download:Download URLs, extract text, save as markdown'
                'extract-conversations:Extract Claude Code conversation history'
                'gh-search:Search GitHub for code examples'
                'gemini-research:Google Search via Gemini CLI'
                'parallel-search:Multi-angle web research'
                'setup:Setup all-agents for user or project'
                'uninstall:Uninstall all-agents'
                'sync-context:Sync context folder to target project'
                'task:Task management utilities'
                'story:Story management utilities'
                'ralph:Autonomous development framework'
                'completion:Generate shell completion scripts'
            )
            _describe 'command' commands
            ;;
        args)
            case $words[1] in
                download)
                    _arguments \\
                        '(-o --output)'{-o,--output}'[Output filename]:filename:_files' \\
                        '(-d --dir)'{-d,--dir}'[Output directory]:directory:_files -/' \\
                        '*:url:_urls'
                    ;;
                extract-conversations)
                    _arguments \\
                        '(-l --limit)'{-l,--limit}'[Number of recent conversations]:number:' \\
                        '(-o --output)'{-o,--output}'[Output file]:file:_files' \\
                        '(-s --skip)'{-s,--skip}'[Skip N most recent]:number:'
                    ;;
                gh-search)
                    _arguments \\
                        '1:query:'
                    ;;
                gemini-research)
                    _arguments \\
                        '--mode[Research mode]:mode:(quick deep code)' \\
                        '1:query:'
                    ;;
                parallel-search)
                    _arguments \\
                        '--objective[Main search objective]:objective:' \\
                        '*--queries[Additional search queries]:query:' \\
                        '--processor[Processing level]:processor:(base pro)' \\
                        '--max-results[Maximum results]:number:' \\
                        '--max-chars[Max chars per excerpt]:number:'
                    ;;
                setup)
                    _arguments \\
                        '--user[Setup CLI globally]' \\
                        '--project[Setup current project]'
                    ;;
                uninstall)
                    _arguments \\
                        '--user[Remove aaa symlink]' \\
                        '--project[Remove context/ symlink]'
                    ;;
                sync-context)
                    _arguments \\
                        '(-t --target)'{-t,--target}'[Target directory]:directory:_files -/' \\
                        '(-w --watch)'{-w,--watch}'[Watch for changes]'
                    ;;
                task)
                    _aaa_task
                    ;;
                story)
                    _aaa_story
                    ;;
                ralph)
                    _aaa_ralph
                    ;;
                completion)
                    _arguments '1:shell:(bash zsh fish)'
                    ;;
            esac
            ;;
    esac
}

_aaa_task() {
    local -a subcommands
    subcommands=(
        'create:Create empty task file with auto-numbered name'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                create)
                    _arguments \\
                        '(-d --dir)'{-d,--dir}'[Custom tasks directory]:directory:_files -/' \\
                        '(-s --story)'{-s,--story}'[Link task to story number]:story:' \\
                        '1:name:'
                    ;;
            esac
            ;;
    esac
}

_aaa_story() {
    local -a subcommands
    subcommands=(
        'create:Create empty story file with auto-numbered name'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                create)
                    _arguments \\
                        '(-d --dir)'{-d,--dir}'[Custom stories directory]:directory:_files -/' \\
                        '1:name:'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph() {
    local -a subcommands
    subcommands=(
        'build:Run subtask iteration loop'
        'plan:Planning tools for vision, roadmap, stories, tasks'
        'review:Review planning artifacts for quality and gaps'
        'milestones:List available milestones'
        'status:Display build status and progress'
        'calibrate:Run calibration checks'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                build)
                    _arguments \\
                        '--subtasks[Subtasks file path]:file:_files -g "*.json"' \\
                        '(-p --print)'{-p,--print}'[Print prompt without executing]' \\
                        '(-i --interactive)'{-i,--interactive}'[Pause between iterations (legacy)]' \\
                        '(-s --supervised)'{-s,--supervised}'[Supervised mode: watch each iteration]' \\
                        '(-H --headless)'{-H,--headless}'[Headless mode: JSON output + logging]' \\
                        '--max-iterations[Max retry attempts]:number:' \\
                        '--validate-first[Run pre-build validation]'
                    ;;
                plan)
                    _aaa_ralph_plan
                    ;;
                review)
                    _aaa_ralph_review
                    ;;
                milestones)
                    _arguments '--json[Output as JSON]'
                    ;;
                status)
                    _arguments '1:subtasks-path:_files -g "*.json"'
                    ;;
                calibrate)
                    _arguments \\
                        '--force[Skip approval]' \\
                        '--review[Require approval]' \\
                        '1:subcommand:(intention technical improve all)'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph_plan() {
    local -a subcommands
    subcommands=(
        'vision:Interactive vision planning'
        'roadmap:Interactive roadmap planning'
        'stories:Story planning for a milestone'
        'tasks:Task planning for a story'
        'subtasks:Generate subtasks for a task'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                vision|roadmap)
                    # No additional arguments
                    ;;
                stories)
                    _arguments \\
                        '--milestone[Milestone file]:milestone:_files -g "*.md"' \\
                        '(-a --auto)'{-a,--auto}'[Use auto mode (alias for --supervised)]' \\
                        '(-s --supervised)'{-s,--supervised}'[Supervised mode: watch chat]' \\
                        '(-H --headless)'{-H,--headless}'[Headless mode: JSON output + logging]'
                    ;;
                tasks)
                    _arguments \\
                        '--story[Story file]:story:_files -g "*.md"' \\
                        '--milestone[Milestone file]:milestone:_files -g "*.md"' \\
                        '(-a --auto)'{-a,--auto}'[Use auto mode (alias for --supervised)]' \\
                        '(-s --supervised)'{-s,--supervised}'[Supervised mode: watch chat]' \\
                        '(-H --headless)'{-H,--headless}'[Headless mode: JSON output + logging]'
                    ;;
                subtasks)
                    _arguments \\
                        '--task[Task file]:task:_files -g "(*.md|*(/))"' \\
                        '(-s --supervised)'{-s,--supervised}'[Supervised mode (default)]' \\
                        '(-H --headless)'{-H,--headless}'[Headless mode: JSON output + logging]'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph_review() {
    local -a subcommands
    subcommands=(
        'stories:Review stories for a milestone'
        'roadmap:Review roadmap milestones'
        'gap:Cold analysis for gaps and blind spots'
        'tasks:Review tasks for a story (coming soon)'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            # All review commands are supervised-only (no headless)
            case $words[1] in
                stories)
                    _arguments '1:milestone:_files -g "*.md"'
                    ;;
                roadmap)
                    # No additional arguments
                    ;;
                gap)
                    _aaa_ralph_review_gap
                    ;;
                tasks)
                    _arguments '1:story-id:'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph_review_gap() {
    local -a subcommands
    subcommands=(
        'roadmap:Cold analysis of roadmap for gaps'
        'stories:Cold analysis of stories for gaps'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                roadmap)
                    # Gap analysis is supervised-only (no headless)
                    ;;
                stories)
                    # Gap analysis is supervised-only (no headless)
                    _arguments '1:milestone:_files -g "*.md"'
                    ;;
            esac
            ;;
    esac
}

# Register completion - handles zinit/lazy compinit that may reset _comps
# For best results with zinit, load via: zinit ice wait'0b' lucid; zinit snippet ~/.cache/aaa_completion.zsh
autoload -Uz add-zsh-hook
_aaa_comp_register() {
    if (( \$+functions[compdef] )) && [[ "\$_comps[aaa]" != "_aaa" ]]; then
        compdef _aaa aaa 2>/dev/null
    fi
    (( ++_aaa_comp_n > 5 )) && {
        add-zsh-hook -d precmd _aaa_comp_register
        unset _aaa_comp_n
        unfunction _aaa_comp_register 2>/dev/null
    }
}
_aaa_comp_n=0
add-zsh-hook precmd _aaa_comp_register
(( \$+functions[compdef] )) && compdef _aaa aaa 2>/dev/null
`;
}
