/**
 * Zsh completion script generator for aaa CLI
 *
 * Features:
 * - #compdef aaa header for automatic loading
 * - _arguments with state machine for nested commands
 * - _describe for command descriptions
 * - Dynamic completions via `aaa __complete <type>`
 */
export default function generateZshCompletion(): string {
  return `#compdef aaa
compdef _aaa aaa
# aaa zsh completion
# Generated by: aaa completion zsh
# Install: source <(aaa completion zsh)
# For oh-my-zsh: aaa completion zsh > ~/.oh-my-zsh/completions/_aaa

_aaa() {
    local curcontext="$curcontext" state line
    typeset -A opt_args

    _arguments -C \\
        '(-h --help)'{-h,--help}'[Show help]' \\
        '(-V --version)'{-V,--version}'[Show version]' \\
        '1: :->command' \\
        '*:: :->args'

    case $state in
        command)
            local -a commands
            commands=(
                'download:Download URLs, extract text, save as markdown'
                'extract-conversations:Extract Claude Code conversation history'
                'gh-search:Search GitHub for code examples'
                'gemini-research:Google Search via Gemini CLI'
                'parallel-search:Multi-angle web research'
                'setup:Setup all-agents for user or project'
                'uninstall:Uninstall all-agents'
                'sync-context:Sync context folder to target project'
                'task:Task management utilities'
                'story:Story management utilities'
                'ralph:Autonomous development framework'
                'completion:Generate shell completion scripts'
            )
            _describe 'command' commands
            ;;
        args)
            case $words[1] in
                download)
                    _arguments \\
                        '(-o --output)'{-o,--output}'[Output filename]:filename:_files' \\
                        '(-d --dir)'{-d,--dir}'[Output directory]:directory:_files -/' \\
                        '*:url:_urls'
                    ;;
                extract-conversations)
                    _arguments \\
                        '(-l --limit)'{-l,--limit}'[Number of recent conversations]:number:' \\
                        '(-o --output)'{-o,--output}'[Output file]:file:_files' \\
                        '(-s --skip)'{-s,--skip}'[Skip N most recent]:number:'
                    ;;
                gh-search)
                    _arguments \\
                        '1:query:'
                    ;;
                gemini-research)
                    _arguments \\
                        '--mode[Research mode]:mode:(quick deep code)' \\
                        '1:query:'
                    ;;
                parallel-search)
                    _arguments \\
                        '--objective[Main search objective]:objective:' \\
                        '*--queries[Additional search queries]:query:' \\
                        '--processor[Processing level]:processor:(base pro)' \\
                        '--max-results[Maximum results]:number:' \\
                        '--max-chars[Max chars per excerpt]:number:'
                    ;;
                setup)
                    _arguments \\
                        '--user[Setup CLI globally]' \\
                        '--project[Setup current project]'
                    ;;
                uninstall)
                    _arguments \\
                        '--user[Remove aaa symlink]' \\
                        '--project[Remove context/ symlink]'
                    ;;
                sync-context)
                    _arguments \\
                        '(-t --target)'{-t,--target}'[Target directory]:directory:_files -/' \\
                        '(-w --watch)'{-w,--watch}'[Watch for changes]'
                    ;;
                task)
                    _aaa_task
                    ;;
                story)
                    _aaa_story
                    ;;
                ralph)
                    _aaa_ralph
                    ;;
                completion)
                    _arguments '1:shell:(bash zsh fish)'
                    ;;
            esac
            ;;
    esac
}

_aaa_task() {
    local -a subcommands
    subcommands=(
        'create:Create empty task file with auto-numbered name'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                create)
                    _arguments \\
                        '(-d --dir)'{-d,--dir}'[Custom tasks directory]:directory:_files -/' \\
                        '(-s --story)'{-s,--story}'[Link task to story number]:story:' \\
                        '1:name:'
                    ;;
            esac
            ;;
    esac
}

_aaa_story() {
    local -a subcommands
    subcommands=(
        'create:Create empty story file with auto-numbered name'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                create)
                    _arguments \\
                        '(-d --dir)'{-d,--dir}'[Custom stories directory]:directory:_files -/' \\
                        '1:name:'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph() {
    local -a subcommands
    subcommands=(
        'build:Run subtask iteration loop'
        'plan:Planning tools for vision, roadmap, stories, tasks'
        'milestones:List available milestones'
        'status:Display build status and progress'
        'calibrate:Run calibration checks'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                build)
                    _arguments \\
                        '--subtasks[Subtasks file path]:file:_files -g "*.json"' \\
                        '(-p --print)'{-p,--print}'[Print prompt without executing]' \\
                        '(-i --interactive)'{-i,--interactive}'[Pause between iterations]' \\
                        '--max-iterations[Max retry attempts]:number:' \\
                        '--validate-first[Run pre-build validation]'
                    ;;
                plan)
                    _aaa_ralph_plan
                    ;;
                milestones)
                    _arguments '--json[Output as JSON]'
                    ;;
                status)
                    _arguments '1:subtasks-path:_files -g "*.json"'
                    ;;
                calibrate)
                    _arguments \\
                        '--force[Skip approval]' \\
                        '--review[Require approval]' \\
                        '1:subcommand:(intention technical improve all)'
                    ;;
            esac
            ;;
    esac
}

_aaa_ralph_plan() {
    local -a subcommands
    subcommands=(
        'vision:Interactive vision planning'
        'roadmap:Interactive roadmap planning'
        'stories:Story planning for a milestone'
        'tasks:Task planning for a story'
        'subtasks:Generate subtasks for a task'
    )

    _arguments -C \\
        '1: :->subcmd' \\
        '*:: :->args'

    case $state in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case $words[1] in
                vision|roadmap)
                    # No additional arguments
                    ;;
                stories)
                    _arguments \\
                        '--milestone[Milestone name]:milestone:_aaa_milestones' \\
                        '(-a --auto)'{-a,--auto}'[Use auto mode]'
                    ;;
                tasks)
                    _arguments \\
                        '--story[Story ID]:story:' \\
                        '--milestone[Milestone name]:milestone:_aaa_milestones' \\
                        '(-a --auto)'{-a,--auto}'[Use auto mode]'
                    ;;
                subtasks)
                    _arguments '--task[Task ID]:task:'
                    ;;
            esac
            ;;
    esac
}

_aaa_milestones() {
    local -a milestones
    milestones=("\${(@f)$(aaa __complete milestone 2>/dev/null)}")
    _describe 'milestone' milestones
}

# Don't run completion function when being source-ed or eval-ed
if [ "$funcstack[1]" = "_aaa" ]; then
    _aaa
fi
`;
}
